# Generated by Django 4.2.8 on 2023-12-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="Birth_Date",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="player",
            name="Club_Joining",
            field=models.CharField(),
        ),
    ]
